name: arcane_auth
description: "Authentication Service Provider & UI for Authentication in Arcane Style"
version: 1.2.0
repository: https://github.com/ArcaneArts/arcane_auth
environment:
  sdk: ^3.5.2
  flutter: ">=1.20.0"
dependencies:
  arcane: ^3.5.0
  common_svgs: ^1.0.2
  crypto: ^3.0.6
  desktop_webview_auth: ^0.0.15
  desktop_webview_window: ^0.2.3
  email_validator: ^3.0.0
  fast_log: ^1.0.7
  firebase_auth: ^5.3.4
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  google_sign_in: ^6.2.2
  hive_flutter: ^1.1.0
  http: ^1.2.2
  plugin_platform_interface: ^2.1.8
  rxdart: ^0.28.0
  serviced: ^1.0.1
  sign_in_with_apple: ^6.1.3
  toxic: ^1.3.2
  toxic_flutter: ^1.1.0
  universal_io: ^2.2.2
  webview_flutter: ^4.10.0
flutter:
  plugin:
    implements: arcane_auth
    platforms:
      windows:
        dartPluginClass: SocialSignInDesktop
      macos:
        dartPluginClass: SocialSignInDesktop
      ios:
        dartPluginClass: SocialSignInMobile
      android:
        dartPluginClass: SocialSignInMobile