name: arcane_auth
description: "Authentication Service Provider & UI for Authentication in Arcane Style"
version: 0.0.1
repository: https://github.com/ArcaneArts/arcane_auth
environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"
dependencies:
  arcane: ^3.4.1
  fast_log: ^1.0.7
  firebase_auth: ^5.3.3
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  rxdart: ^0.28.0
  serviced: ^1.0.1
  toxic: ^1.3.2
  toxic_flutter: ^1.1.0
flutter: